### ISSUE TITLE
Way to Track Progress of Processing?

### ISSUE THREAD

**Issue by Millertime72** [Picovoice/leopard#229]
Is there any way to track the progress of the `process` function of `Leopard`? A way to find the percentage complete would be amazing. Maybe with a callback to the `Leopard` object? I'm using Python.

Thanks very much.

**Comment by laves** [comment]
No, unfortunately, there is not currently a way of tracking Leopard's progress in processing a given chunk of audio. You can always break large chunks of audio into smaller ones so that you won't be left waiting for too long. We'll think about adding this to future versions of the engine - thank you.
