### ISSUE TITLE
help with using leopard with pyaudio

### ISSUE THREAD

**Issue by unitedevop** [Picovoice/leopard#34]
So I want to use pyaudio to record from mic detect the sentence and print the text. this is happening in loop but I can't get it to work in other way other than leopard demo package. help me with this

**Comment by mrrostam** [comment]
I am not clear on what exactly is the issue here, can you give me more detail?

**Comment by unitedevop** [comment]
I want a example for using leopard with pyaudio module.

**Comment by unitedevop** [comment]
> I want a example for using leopard with pyaudio module.

I could not find any example for using it with pyaudio module.

**Comment by unitedevop** [comment]
I want the example to work with mic

**Comment by mrrostam** [comment]
For python there is a [mic demo](https://github.com/Picovoice/leopard/blob/master/demo/python/leopard_demo_mic.py) which shows how to use Leopard properly when you have a PCM audio buffer. In that demo PvRecorder is used since it's cross platform and already [satisfied all requirements](https://picovoice.ai/docs/api/leopard-python/#pvleopardleopardprocess), but it should be easy to replace it with PyAudio. You can check out this old [mic demo for Rhino](https://github.com/Picovoice/rhino/blob/d0f533a1c065fde997d4bee30fde64374fe7b61e/demo/python/rhino_demo_mic.py) in which PyAudio is used if you are struggling with PyAudio's configurations.

**Comment by unitedevop** [comment]
> For python there is a [mic demo](https://github.com/Picovoice/leopard/blob/master/demo/python/leopard_demo_mic.py) which shows how to use Leopard properly when you have a PCM audio buffer. In that demo PvRecorder is used since it's cross platform and already [satisfied all requirements](https://picovoice.ai/docs/api/leopard-python/#pvleopardleopardprocess), but it should be easy to replace it with PyAudio. You can check out this old [mic demo for Rhino](https://github.com/Picovoice/rhino/blob/d0f533a1c065fde997d4bee30fde64374fe7b61e/demo/python/rhino_demo_mic.py) in which PyAudio is used if you are struggling with PyAudio's configurations.

I have tried using this method before but how can I frame length
