### ISSUE TITLE
Leopard Implementaiton Issue- React Native and Expo Go: 

### ISSUE THREAD

**Issue by kateottenwess** [Picovoice/leopard#371]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Leopard docs
- [X] I have searched the existing issues for Leopard

### SDK

React Native

### Leopard package version

2.0.2

### Framework version

React Native: 0.72.6 Expo:^49.0.13

### Platform

Windows (x86_64)

### OS/Browser version

Windows 11

### Describe the bug

I am attempting to implement the Leopard STT api into my project that is built using React Native and Expo Go. When calling const leopard = await Leopard.create(accessKey, modelPath);, I get an error stating [Error: unexpected code: undefined, message: Cannot read property 'create' of null], despite me following all of the installation steps correctly and I am verified that my Leopard import is indeed functional (console.log(Leopard) prints [Function Leopard] prior to my create call). Are there compatibility issues with Leopard and Expo? I have also ensured that the accessKey and model path are being correctly passed.

### Steps To Reproduce

1. Import Leopard
2. Use useState to set and use the Leopard instance
3. Define an asynchronous function to get an instance of Leopard
4. Use leopardInstance in stopRecording() function when recording is done and audio needs to be transcribed
The txt file is a simple app.js file for a basic react native & expo set up that is throwing this error
[leopard_error.txt](https://github.com/Picovoice/leopard/files/14767072/leopard_error.txt)

### Expected Behavior

I would expect the audio file being passed (which in my case is just a tester .wav file) to be transcribed, and I would expected for the leopardInstance to be set correctly as everything is being done as per the docs.

**Comment by albho** [comment]
Looking at the example you provided - `.processFile()` is an async function, so you'll need to add an `await`.

If that doesn't solve the issue, you can give our [demo](https://github.com/Picovoice/leopard?tab=readme-ov-file#react-native-demo) a try and see if that works on your device.

**Comment by laves** [comment]
Closed due to inactivity

**Comment by ckhicks** [comment]
@kateottenwess I slammed my head against this for days using Expo and just got it working. Errors thrown about `create` being `null` are due to missing model files.

The asset linking pipeline is a little funky compared with bare RN projects in the docs - here's what I did:
1. Change filenames of Leopard models to `.db` to fix prebuild support errors with `.pv` file extensions
2. Place models in a dir at the project root (likely not needed but I wanted it outside of assets)
3. Build a new dev version (very important!)
4. Link the models using ONLY the filename (ex: `leopard_params.db`) without any other path parameters
5. Use a `ref` to store the Leopard instance (more durable than state)

After doing those steps, I saw `{"_handle": "Leopard.Leopard", "_sampleRate": 16000, "_version": "2.0.0"}` in my console for the first time. Hope it helps!
